### ISSUE TITLE
Does not start on Openshift DIY 0.1

### ISSUE THREAD

**Issue by prestonvanloon** [DataDog/datadog-openshift#7]
```
[ddmonitor-mpowered.rhcloud.com bin]\> $OPENSHIFT_DATADOG_DIR/dd-agent/bin/agent start
Starting supervisor
/var/lib/openshift/569fe4ed0c1e6686e000013d/datadog//dd-agent/bin/agent: line 85: supervisord: command not found
```
This was a fresh install 
```
ddmonitor @ http://ddmonitor-mpowered.rhcloud.com/ (uuid: 569fe4ed0c1e6686e000013d)
-----------------------------------------------------------------------------------
  Domain:     mpowered
  Created:    9:50 PM
  Gears:      1 (defaults to small)
  Git URL:    <--removed-->
  SSH:        <--removed-->
  Deployment: auto (on git push)

  diy-0.1 (Do-It-Yourself 0.1)
  ----------------------------
    Gears: Located with datadog-datadog-5.0.0

  datadog-datadog-5.0.0 (Datadog Agent 5.0.0)
  -------------------------------------------
    From:    http://cartreflect-claytondev.rhcloud.com/github/datadog/datadog-openshift
    Website: https://github.com/DataDog/datadog-openshift
    Gears:   Located with diy-0.1
```

**Comment by Martiflex** [comment]
Update:

> Here's the entire process to replicate my openshift issue. (Let me preface this with: it works now!!!)
> 
> # Create the DD monitor app 
> rhc app create ddmonitor diy-0.1
> 
> # Set the environment variable 
> rhc set-env DATADOG_API_KEY=<key>-a ddmonitor
> 
> # Add the cartridge 
> rhc cartridge-add http://cartreflect-claytondev.rhcloud.com/github/datadog/datadog-openshift -a ddmonitor
> 
> # SSH into the gear 
> rhc ssh ddmonitor
> 
> # start the monitor 
> $OPENSHIFT_DATADOG_DIR/bin/control start
> 
> # check the status 
> $OPENSHIFT_DATADOG_DIR/bin/control status
> 
> And I see some agents running! Previously it wouldn't work. Maybe a failed download of the cartridge? I'm not sure. When I would run the control start command it would say "starting the agent..." then when I ran the status command it would say no agents running. No error or anything. So I looked into what the start command did and tried to run that. That's how I go the "supervisord" not defined or whatever.

**Comment by prestonvanloon** [comment]
Thanks @Martiflex. This is working for me now.
